<Project>
	<Target Name="A2v10WorkflowEngineCopySqlAssets" AfterTargets="Build"
			Condition="'$(A2v10WorkflowEngineCopySql)' != 'false'">
		<ItemGroup>
			<A2v10WorkflowEngineSqlFiles Include="$(MSBuildThisFileDirectory)..\contentFiles\sql\*" />
		</ItemGroup>
		<Copy SourceFiles="@(A2v10WorkflowEngineSqlFiles)"
			  DestinationFolder="$(MSBuildProjectDirectory)\_assets\sql"
			  SkipUnchangedFiles="true" />
	</Target>
</Project>